{% set name = "pytest-pycodestyle" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 27cfebd52774ad55cceadce959913892b3b0989fc02400ef76a004a8b32ab5c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - setuptools
    - pip
  run:
    - python >=3.6,<4
    - pytest >=5.4
    - pycodestyle
    - py

test:
  requires:
    - pip
  commands:
    - pip check
    - pytest --traceconfig | grep pytest-pycodestyle-{{ version }}

about:
  home: https://github.com/henry0312/pytest-pycodestyle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin to run pycodestyle
  description: pytest plugin to run pycodestyle

  doc_url: https://github.com/henry0312/pytest-pycodestyle
  dev_url: https://github.com/henry0312/pytest-pycodestyle

extra:
  recipe-maintainers:
    - ma-sadeghi
