{% set name = "pytest-pycodestyle" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd0060039e12a59b521da8e57e17133c965566dd8d17631e589e7545238829ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<4
    - pytest >=5.4
    - pycodestyle
    - py

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --traceconfig | grep pytest-pycodestyle-{{ version }}

about:
  home: https://github.com/henry0312/pytest-pycodestyle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin to run pycodestyle
  description: pytest plugin to run pycodestyle

  doc_url: https://github.com/henry0312/pytest-pycodestyle
  dev_url: https://github.com/henry0312/pytest-pycodestyle

extra:
  recipe-maintainers:
    - ma-sadeghi
